Antonio/29/03
shdwplay/BlackBirdREACT pull request #14
Opened 2019-03-29 16:52 UTC by awpellegrini

controllate il codice please!

2019-03-29 17:00 UTC, Takeno requested changes

2019-03-29 17:00 UTC, Takeno commented on src/App.js
> +      : this.setState({ searchToggle: true, querystr: "" });
Per questo toggle è morto un gattino.

2019-03-29 17:00 UTC, Takeno commented on src/App.js
> +    aux[this.state.highlightedCard][option] = !aux[this.state.highlightedCard][
E' molto incomprensibile. Se proprio è l'unico modo, lascia un commento per evitare di farti odiare da qualcuno domani.

2019-03-29 17:00 UTC, Takeno commented on src/components/Button.js
>  export default Button;
Le prop-types ce le siamo dimenticate

2019-03-29 17:00 UTC, Takeno commented on src/components/Card.js
> +        getUnread(props.data.numUnread) + " " + getActive(props.isActive)
Forse queste funzioni di utility sono inutili se usate la libreria `classnames` ed evito di andare su diversi file per capire

2019-03-29 17:00 UTC, Takeno commented on src/utils.js
> +export { setOption };
Anziché fare l'export di tutte le singole, potete esportarle direttamente nella dichiarazione:

`export const setOption = ...`

2019-03-29 17:02 UTC, Takeno commented
Considerate l'utilizzo della libreria https://github.com/JedWatson/classnames per le classi css condizionali

2019-03-30 14:34 UTC, awpellegrini commented on src/App.js
> +    aux[this.state.highlightedCard][option] = !aux[this.state.highlightedCard][
'invoking this method with "favourites" or "silenced" as an argument will toggle (update state) the corresponding boolean value of the current highlighted chat card'

2019-03-30 14:34 UTC, awpellegrini commented on src/components/Button.js
>  export default Button;
Back.propTypes = {
  onClick: PropTypes.func.isRequired
};

2019-03-30 14:35 UTC, awpellegrini commented on src/utils.js
> +export { setOption };
molto comodo, grazie!

2019-03-30 16:48 UTC, Takeno commented on src/App.js
> +    aux[this.state.highlightedCard][option] = !aux[this.state.highlightedCard][
Da mettere nel codice però :)

2019-03-30 16:49 UTC, Takeno commented
Per risolvere le issue segnalate durante la review, dovete apportare le modifiche sul file, fare un commit sulla stessa branch e fare push. In questo modo si aggiorna la PR e le modifiche richieste spariscono.

2019-03-30 16:50 UTC, Takeno commented on src/components/Button.js
>  export default Button;
Vanno nel codice, non nei commenti di github

2019-03-30 17:09 UTC, Takeno requested changes

2019-03-30 17:09 UTC, Takeno commented on src/components/Card.js
> +    : (cardClass += " Card-read");
Fare un'assegnazione dentro un operatore ternario è al limite del carcere.
Usate un if-else oppure con
```
classnames({
'Card': true,
'Card-unread': props.data.numUnread > 0,
'Card-read': props.data.numUnread === 0
);
```

2019-03-30 17:09 UTC, Takeno commented on src/utils.js
>    else {
Se usiamo if-return, non c'è bisogno degli else

2019-03-30 17:09 UTC, Takeno commented on src/utils.js
>            <img alt="notifications" src={notificationsOff} />
Se l'unica modifica di questo enorme if-else è `notificationsOn`/`notificationsOff` forse basterebbe un ternario all'interno della proprietà `src`, no?

2019-04-01 09:15 UTC, merged